Use separate function for Touch ID sudo

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -20,12 +20,12 @@ echo
 
 # If macOS
 if [[ "$(uname)" == "Darwin" ]]; then
-  echo "Setting path"
+  title "Setting initial path."
   export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"
 
   # Install brew
   if test ! $(which brew); then
-    title "Installing Homebrew..."
+    title "Installing Homebrew."
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     echo
   fi
@@ -33,11 +33,10 @@ if [[ "$(uname)" == "Darwin" ]]; then
   # Get Brew directory
   BREW_PREFIX=$(brew --prefix)
 
-  # Disable Brew analytics
+  title "Disabling Brew analytics."
   brew analytics off
 
-  # Install brew packages
-  title "Installing software..."
+  title "Installing Brew software."
   brew bundle | indent
   echo
   brew doctor
@@ -48,29 +47,30 @@ if [[ "$(uname)" == "Darwin" ]]; then
   # Link Brew OpenJDK
   sudo ln -sfn $BREW_PREFIX/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
 
-  # Ensure zsh is a valid shell option
+  # Ensure Brew Zsh is a valid shell option
   if ! cat /etc/shells | grep $BREW_PREFIX/bin/zsh > /dev/null; then
-    title "Adding zsh to list of allowed shells..."
-    sudo sh -c 'echo $BREW_PREFIX/bin/zsh >> /etc/shells'
+    title "Adding Homebrew Zsh to list of allowed shells."
+    sudo sh -c 'echo ${BREW_PREFIX}/bin/zsh >> /etc/shells'
     echo
   fi
 
-  # Use Touch ID for sudo
-  if ! cat /etc/pam.d/sudo | grep pam_tid > /dev/null; then
-    sudo sed -i '' '2i\
-auth       sufficient     pam_tid.so
-' /etc/pam.d/sudo
+  # Ensure Brew Bash is a valid shell option
+  if ! cat /etc/shells | grep $BREW_PREFIX/bin/bash > /dev/null; then
+    title "Adding Homebrew Bash to list of allowed shells."
+    sudo sh -c 'echo ${BREW_PREFIX}/bin/bash >> /etc/shells'
+    echo
   fi
 
-  title "Configuring macOS..."
-  ./scripts/configure-macos
-  echo "Defaults configured!" | indent
+  title "Use Touch ID for sudo."
+  sudo ./scripts/touchid_sudo.sh || echo "Configuring sudo failed!"
+  
+  title "Configuring macOS defaults."
+  ./scripts/configure-macos || echo "Configuring defaults failed!"
   echo
-
-fi
+fi # End of macOS section
 
 # Install symlinks
-title "Configuring software..."
+title "Configuring symlinks."
 ./scripts/install-symlinks
 
 # Install yarn packages
@@ -83,12 +83,12 @@ title "Configuring software..."
 # Check that we are using zsh
 if [[ "$SHELL" != *"zsh"* ]]; then
   if [[ "$(uname)" == "Darwin" ]]; then
-    title "Changing user shell to zsh..."
+    title "Changing user shell to Zsh."
     chsh -s $BREW_PREFIX/bin/zsh
-    echo "Your shell has been changed to zsh, please restart your terminal or tab" | indent
+    echo "Your shell is changed to Zsh. Restart your terminal or tab." | indent
     echo
   else
-    echo "You are not using zsh, after installing, please run 'chsh -s /path/to/zsh'" | indent
+    echo "You are not using Zsh. After installing, run 'chsh -s /path/to/zsh'." | indent
     echo
   fi
 fi
